# At a specific moment, analyze the traffic throughput of each link (ISLs and GSLs) under the network topology and traffic conditions.
# Network Topology: User blocks connect to a satellite; satellites form Dynamic Flipping topology
#   (2 intra-orbit ISLs + 0-1 inter-orbit ISL per satellite = at most 3 ISLs).
# Traffic: Based on the Starlink traffic of each block from CloudFlare, flows probabilistically
#   increasing by 0.5M each sampling time (ISL capacity 20Gbps; GSL Uplink/Downlink: 4Gbps).
# Topology loaded from CDN JSON output (topology.json) generated by write_skyfall_tle.py + generate.py.
# SKYFALL timeslots are 1-second; CDN frames are 15-second — mapped as frame = timeslot // CDN_STEP.

import math
import sys
import numpy as np
import random
import json
import os
from collections import deque

# Constants
RADIUS = 6371
Flow_size = 0.5  # 0.5M
CDN_STEP = 15    # CDN topology frame interval in seconds

f = open("../config.json", "r", encoding='utf8')
table = json.load(f)
cons_name = table["Name"]
altitude = int(table["Altitude (km)"])
num_of_orbit = table["# of orbit"]
sat_of_orbit = table["# of satellites"]
inclination = table["Inclination"]
topology_json = table.get("topology_json", "../topology_test.json")
sat_num = num_of_orbit * sat_of_orbit
user_num = inclination * 2 * 360

sat_pos_car = []
user_pos_car = []
GS_pos_car = []
pop_count = []
user_connect_sat = []
sat_connect_gs = []
gsl_occurrence = [[] for i in range(sat_num)]
gsl_occurrence_num = [-1 for i in range(sat_num)]

# Routing: path[i] = next hop satellite from i toward nearest GS-connected satellite
# (same semantics as generate_flow_grid.py but populated by BFS, not Manhattan heuristic)
path = [-1 for i in range(sat_num)]

link_utilization_ratio = 100
isl_capacity = 20480
uplink_capacity = downlink_capacity = 4096
bandwidth_isl = isl_capacity * link_utilization_ratio / 100
bandwidth_uplink = uplink_capacity * link_utilization_ratio / 100
bandwidth_downlink = uplink_capacity * link_utilization_ratio / 100

# Per-satellite traffic accumulators (GSLs stay per-satellite like grid/circle)
isl_traffic = [0] * sat_num
downlink_traffic = [0] * sat_num
uplink_traffic = [0] * sat_num
sat_cover_pop = [0] * sat_num
sat_cover_user = [[] for i in range(sat_num)]

flows = []
flows_selected = {}
flows_num = 0
flows_cumulate_weight = []
flows_sum_weight = 0

# Per-frame topology state (rebuilt each timeslot via load_frame())
neighbors = {}        # sat_idx -> list of neighbor sat_idx
link_id_map = {}      # (sat_i, sat_j) -> index into link_traffic_isl[]
link_traffic_isl = [] # traffic per ISL edge (indexed by link_id_map values)


def cir_to_car_np(lat, lng, h):
    x = (RADIUS + h) * math.cos(math.radians(lat)) * math.cos(math.radians(lng))
    y = (RADIUS + h) * math.cos(math.radians(lat)) * math.sin(math.radians(lng))
    z = (RADIUS + h) * math.sin(math.radians(lat))
    return np.array([x, y, z])


# ── Topology loading ──────────────────────────────────────────────────────────

def load_frame(topo: dict, time_slot: int):
    """
    Load the CDN topology frame corresponding to SKYFALL timeslot.
    Rebuilds neighbors dict and link_id_map for add_flow() to use.
    CDN frames are 15s; SKYFALL timeslots are 1s: frame_idx = time_slot // CDN_STEP.
    """
    global neighbors, link_id_map, link_traffic_isl

    frame_idx = time_slot // CDN_STEP
    frames = topo["frames"]
    frame_idx = min(frame_idx, len(frames) - 1)   # clamp to last frame
    frame = frames[frame_idx]

    all_links = frame["intra_orbit_links"] + frame["inter_orbit_links"]

    neighbors = {}
    link_id_map = {}
    for idx, (a, b) in enumerate(all_links):
        neighbors.setdefault(a, []).append(b)
        neighbors.setdefault(b, []).append(a)
        link_id_map[(a, b)] = idx
        link_id_map[(b, a)] = idx

    link_traffic_isl = [0] * len(all_links)


# ── BFS routing ───────────────────────────────────────────────────────────────

def bfs_next_hop(source: int) -> int:
    """
    BFS from source over current frame's adjacency (neighbors dict).
    Returns the first hop toward the nearest GS-connected satellite,
    or source itself if source is already GS-connected,
    or -1 if no GS-connected satellite is reachable.
    """
    if sat_connect_gs[source] != -1:
        return source
    visited = {source: None}
    queue = deque([source])
    while queue:
        node = queue.popleft()
        if sat_connect_gs[node] != -1:
            # Trace back to the first hop from source
            cur = node
            while visited[cur] != source:
                cur = visited[cur]
            return cur
        for nb in neighbors.get(node, []):
            if nb not in visited:
                visited[nb] = node
                queue.append(nb)
    return -1   # no reachable GS-connected satellite


def build_routing():
    """
    Populate path[] for the current frame using BFS.
    Equivalent to floyd() in generate_flow_grid.py but topology-agnostic.
    Also populates gsl_occurrence like floyd() does.
    """
    global path, gsl_occurrence
    gsl_occurrence = [[] for _ in range(sat_num)]

    for sat_idx in range(sat_num):
        path[sat_idx] = bfs_next_hop(sat_idx)

    # Walk each satellite's path to its landing satellite, assign user coverage
    for sat_idx in range(sat_num):
        landing = path[sat_idx]
        if landing == -1:
            continue
        # Follow hops until landing (path[x] == x means x is the lander)
        cur = sat_idx
        while path[cur] != cur and path[cur] != -1:
            cur = path[cur]
        for item in sat_cover_user[sat_idx]:
            gsl_occurrence[cur].append(item)


# ── Flow simulation ───────────────────────────────────────────────────────────

def init_flows():
    global flows, flows_sum_weight, flows_cumulate_weight, flows_num
    flows = []
    flows_sum_weight = 0
    flows_cumulate_weight = []
    for block in range(inclination * 2 * 360):
        if pop_count[block] == 0:
            continue
        weight = math.ceil(pop_count[block])
        flows.append([block, weight])
        flows_sum_weight += weight
        flows_cumulate_weight.append(flows_sum_weight)
    flows_num = len(flows_cumulate_weight)


def get_one_flow(cumulate_weight, num, sum_weight):
    rand = random.randint(1, sum_weight)
    low, high = 0, num - 1
    while low < high:
        mid = (low + high) >> 1
        if rand > cumulate_weight[mid]:
            low = mid + 1
        elif rand < cumulate_weight[mid]:
            high = mid
        else:
            return mid
    return low


def _apply_flow(src_block: int, rate: float, sign: int):
    """
    Walk the path from src_block's satellite to its landing GS,
    adding sign*rate to each ISL edge and GSL along the way.
    sign = +1 to add, -1 to remove.
    """
    src_sat = user_connect_sat[src_block]
    if src_sat == -1:
        return
    from_sat = src_sat
    if path[from_sat] == -1:
        return
    while True:
        to_sat = path[from_sat]
        if to_sat != from_sat:
            lid = link_id_map.get((from_sat, to_sat), -1)
            if lid == -1:
                # Satellite is in re-acquisition or topology changed; skip ISL
                break
            link_traffic_isl[lid] += sign * rate
            isl_traffic[from_sat] += sign * rate
            from_sat = to_sat
        else:
            break
    uplink_traffic[src_sat] += sign * rate
    downlink_traffic[from_sat] += sign * rate


def add_flow(src_block: int, rate: float = Flow_size) -> int:
    src_sat = user_connect_sat[src_block]
    if src_sat == -1:
        return -1
    if path[src_sat] == -1:
        return 0

    _apply_flow(src_block, rate, +1)

    # Find landing satellite (follow path to fixpoint)
    landing = src_sat
    while path[landing] != landing and path[landing] != -1:
        landing = path[landing]

    if downlink_traffic[landing] < downlink_capacity:
        return 0
    else:
        # Overloaded — roll back
        _apply_flow(src_block, rate, -1)
        return -1


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    bound = 3.743333 * 299792.458 * 0.001
    time_slot = int(sys.argv[1])

    # Load CDN topology
    with open(topology_json) as f_topo:
        print(f"Loading topology from {topology_json}...")
        topo = json.load(f_topo)

    print(f"generating Dynamic Flipping traffic for timeslot: {time_slot} "
          f"(CDN frame {time_slot // CDN_STEP})...")

    # Load satellite positions (same format as grid/circle)
    pos_filename = '../' + cons_name + '/sat_lla/%s.txt' % time_slot
    with open(pos_filename, 'r') as fr:
        for line in fr.readlines():
            satPos = line.split(',')
            sat_pos_car.append(
                cir_to_car_np(float(satPos[0]), float(satPos[1]), float(satPos[2])))
    sat_pos_car = np.array(sat_pos_car)

    # Load user positions
    for lat in range(inclination, -inclination, -1):
        for lon in range(-180, 180, 1):
            user_pos_car.append(cir_to_car_np(lat - 0.5, lon + 0.5, 0))
    user_pos_car = np.array(user_pos_car)

    # Load traffic distribution
    with open('./starlink_count.txt', 'r') as fr:
        lines = fr.readlines()
        for row in range(90 - inclination, 90 + inclination):
            pop_count.extend([float(x) for x in lines[row].split(' ')[:-1]] + [0])

    # Satellite each block connects to
    for user_id in range(inclination * 2 * 360):
        dis2 = np.sqrt(np.sum(np.square(sat_pos_car - user_pos_car[user_id]), axis=1))
        if min(dis2) > bound:
            user_connect_sat.append(-1)
            continue
        min_dis_sat = int(np.argmin(dis2))
        user_connect_sat.append(min_dis_sat)
        if pop_count[user_id] > 0:
            sat_cover_pop[min_dis_sat] += pop_count[user_id]
            sat_cover_user[min_dis_sat].append(user_id)

    # Load GS positions
    with open("./GS.json", "r", encoding='utf8') as f_gs:
        GS_info = json.load(f_gs)
    for key in GS_info:
        GS_pos_car.append(
            cir_to_car_np(float(GS_info[key]['lat']), float(GS_info[key]['lng']), 0))
    GS_pos_car = np.array(GS_pos_car)

    # GS each satellite connects to
    for sat_id in range(sat_num):
        dis2 = np.sqrt(np.sum(np.square(GS_pos_car - sat_pos_car[sat_id]), axis=1))
        if min(dis2) > bound:
            sat_connect_gs.append(-1)
            continue
        sat_connect_gs.append(int(np.argmin(dis2)))

    # Load topology frame for this timeslot
    load_frame(topo, time_slot)

    # Build BFS routing table
    build_routing()

    # Init flows
    init_flows()

    # Simulate traffic
    for _ in range(2000000):
        flow_id = get_one_flow(flows_cumulate_weight, flows_num, flows_sum_weight)
        res = add_flow(flows[flow_id][0])
        if res == -1:
            continue
        flow_pair = (flows[flow_id][0], flows[flow_id][1])
        if flow_pair in flows_selected:
            flows_selected[flow_pair] += Flow_size
        else:
            flows_selected[flow_pair] = Flow_size

    # Save outputs (same structure as +grid_data, under flipping_data/)
    out_dir = '../' + cons_name + '/flipping_data/link_traffic_data/' + str(time_slot)
    os.system("mkdir -p " + out_dir)

    isl_traffic_arr = np.array(isl_traffic, dtype=int)
    np.savetxt(out_dir + '/isl_traffic.txt', isl_traffic_arr, fmt='%d')

    downlink_traffic_arr = np.array(downlink_traffic, dtype=int)
    np.savetxt(out_dir + '/downlink_traffic.txt', downlink_traffic_arr, fmt='%d')

    uplink_traffic_arr = np.array(uplink_traffic, dtype=int)
    np.savetxt(out_dir + '/uplink_traffic.txt', uplink_traffic_arr, fmt='%d')

    sat_connect_gs_arr = np.array(sat_connect_gs, dtype=int)
    np.savetxt(out_dir + '/sat_connect_gs.txt', sat_connect_gs_arr, fmt='%d')

    user_connect_sat_arr = np.array(user_connect_sat, dtype=int)
    np.savetxt(out_dir + '/user_connect_sat.txt', user_connect_sat_arr, fmt='%d')

    id_ = 0
    gs_occurrence_num = [0 for _ in range(len(GS_pos_car))]
    for item in gsl_occurrence:
        gsl_occurrence_num[id_] = len(item) if len(item) > 0 else -1
        if sat_connect_gs[id_] != -1:
            gs_occurrence_num[sat_connect_gs[id_]] += gsl_occurrence_num[id_]
        id_ += 1
    gsl_occurrence_num_arr = np.array(gsl_occurrence_num, dtype=int)
    np.savetxt(out_dir + '/gsl_occurrence_num.txt', gsl_occurrence_num_arr, fmt='%d')

    gs_occurrence_num_arr = np.array(gs_occurrence_num, dtype=int)
    np.savetxt(out_dir + '/gs_occurrence_num.txt', gs_occurrence_num_arr, fmt='%d')

    print(f"Done. Outputs written to {out_dir}")
